module.exports = {
  content: ["./app/**/*.{ts,tsx,jsx,js}"],
  theme: {
    extend: {},
    fontFamily: {
      laila: ["Laila"],
      pacifico: ["Pacifico"],
    },
    colors: {
      blue: [
        null,
        "#EBF2FE",
        "#D7E6FD",
        "#B0CDFB",
        "#89B4FA",
        "#629BF8",
        "#3B82F6",
        "#0B61EE",
        "#084BB8",
        "#063583",
        "#041F4D",
      ],
      red: [
        null,
        "#F7C3CD",
        "#F29FAF",
        "#EF8DA0",
        "#EB6982",
        "#E64564",
        "#E12146",
        "#BF1A3A",
        "#8E132B",
        "#5C0D1C",
        "#2B060D",
      ],
      white: "#fff",
    },
    spacing: {
      "2xs": "0.25rem",
      xs: "0.5rem",
      sm: "0.75rem",
      md: "1rem",
      lg: "1.5rem",
      0: 0,
      30: "1.875rem",
    },
    borderRadius: {
      none: 0,
      sm: "16.5px",
      md: "24.5px",
      full: "50%",
    },
  },
  plugins: [],
};
